# Generated by Django 4.2 on 2025-09-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Command",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "command",
                    models.CharField(
                        choices=[
                            ("forward", "Forward"),
                            ("backward", "Backward"),
                            ("left", "Left"),
                            ("right", "Right"),
                            ("stop", "Stop"),
                        ],
                        default="stop",
                        max_length=20,
                    ),
                ),
                ("speed", models.IntegerField(default=150)),
                ("timestamp", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
